apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  serviceAccountName: example
  containers:
    - name: python
      image: python:3.8
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]
