apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examplecontrollers.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    plural: examplecontrollers
    singular: examplecontroller
    kind: ExampleController
    shortNames:
      - ec
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
